//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 02:56:20 PM IST 
//


package com.paytm.service.online;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.paytm.service.online package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Paytm_QNAME = new QName("http://paytm.com/service/online", "Paytm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.paytm.service.online
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaytmType }
     * 
     */
    public PaytmType createPaytmType() {
        return new PaytmType();
    }

    /**
     * Create an instance of {@link RechargeType }
     * 
     */
    public RechargeType createRechargeType() {
        return new RechargeType();
    }

    /**
     * Create an instance of {@link FeedBackType }
     * 
     */
    public FeedBackType createFeedBackType() {
        return new FeedBackType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaytmType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://paytm.com/service/online", name = "Paytm")
    public JAXBElement<PaytmType> createPaytm(PaytmType value) {
        return new JAXBElement<PaytmType>(_Paytm_QNAME, PaytmType.class, null, value);
    }

}
