//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 02:56:20 PM IST 
//

package com.paytm.service.online;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for paytmType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="paytmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recharge" type="{http://paytm.com/service/online}rechargeType"/>
 *         &lt;element name="User" type="{http://paytm.com/service/online}userType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paytmType", propOrder = { "recharge", "user" })
@XmlRootElement
public class PaytmType {

	@XmlElement(required = true)
	protected RechargeType recharge;
	@XmlElement(name = "User", required = true)
	protected UserType user;

	/**
	 * Gets the value of the recharge property.
	 * 
	 * @return possible object is {@link RechargeType }
	 * 
	 */
	public RechargeType getRecharge() {
		return recharge;
	}

	/**
	 * Sets the value of the recharge property.
	 * 
	 * @param value
	 *            allowed object is {@link RechargeType }
	 * 
	 */
	public void setRecharge(RechargeType value) {
		this.recharge = value;
	}

	/**
	 * Gets the value of the user property.
	 * 
	 * @return possible object is {@link UserType }
	 * 
	 */
	public UserType getUser() {
		return user;
	}

	/**
	 * Sets the value of the user property.
	 * 
	 * @param value
	 *            allowed object is {@link UserType }
	 * 
	 */
	public void setUser(UserType value) {
		this.user = value;
	}

}
